name: Deploy

on:
  # pull_request:
  #   branches:
  #   - deploy
  push:
    branches:
      - deploy/production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/IDG
          git checkout deploy/production
          git reset --hard HEAD
          git pull
          npm install
          npx prisma generate
          npm run build
          npx pm2 restart togaserver.config.cjs
    - name: Notification
      uses: easychen/github-action-server-chan@v1.0.0
      with:
        sendkey: ${{ secrets.SENDKEY }}
        title: "TOGA Backend CI/CD work Notification"
        desp: "Result:${{job.status}}"
