name: Test

on:
  pull_request:
    branches:
      - main
      - dev
      - "dev-**"
  push:
    branches:
      - fix/**
      - feat/**
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup Redis
        uses: supercharge/redis-github-action@1.8.1
        with:
          redis-version: "7.2.4"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CORS_WHITE_LIST: ${{ secrets.CORS_WHITE_LIST }}
          PASSWORD_CRYPT_KEY: "114514"
          JWT_SECRET: "114514"
      - name: Notification
        uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.SENDKEY }}
          title: "TOGA Backend CI/CD work Notification"
          desp: "Test Result:${{job.status}}"
